version: '3'

services:
  server:
      build:
        context: ./server
        dockerfile: Dockerfile_server
      command: python3 -u server.py
      container_name: server
      ports:
        - 50051:50051
      volumes:
        - .:/usr/src/app/server
  client1:
      build:
        context: ./client
        dockerfile: Dockerfile_client
        args:
          id_client: 50050
      command: python3 -u client.py 50050 172.16.238.6
      container_name: client
      ports:
        - 50050:50050
      volumes:
        - .:/usr/src/app/cliente
  client2:
      build:
        context: ./client
        dockerfile: Dockerfile_client
        args:
          id_client: 50049
      command: python3 -u client.py 50049 172.16.238.5
      container_name: client2
      ports:
        - 50049:50049
      volumes:
        - .:/usr/src/app